---
- hosts: 192.168.149.187
  become: true
  become_method: sudo

  tasks:
    - name: install lamp stack
      dnf:
        name: 
          - httpd
          - httpd-devel
          - mysql
          - mysql-server
          - mysql-devel
          - php
          - php-devel
        state: latest 
  

