---
- hosts: all
  become: true
  become_method: sudo
  
  tasks:      
##PHP7.4
    - name: PHP 7.4
        command: {{ item }}
        with_items:
        - sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y
        - sudo dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
        - sudo dnf module enable php:remi-7.4 -y
        - sudo dnf install php php-cli php-common php-mysqlnd -y
