---
- hosts: Rocky
  become: true
  become_method: sudo
  
  tasks:
  - name: Instalar dependencias remi1
    command: 'sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y'
  - name: Instalar dependencias remi2
    command: 'sudo dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y'
  - name: Instalar dependencias remi3
    command: 'sudo dnf module enable php:remi-7.4 -y'
  - name: Instalar dependencias remi4
    command: 'sudo dnf install php php-cli php-common php-mysqlnd -y'
    
    
  - name: Instalar dependencias hhtpd
    command: 'sudo dnf remove @mysql'
  - name: Instalar dependencias hhtpd
    command: 'sudo dnf module reset mysql'
  - name: Instalar dependencias hhtpd
    command: 'sudo dnf module disable mysql -y'
  - name: dependencias mysql-community
    template:
      src: "files/mysql-community.repo"
      dest: "/etc/yum.repos.d/mysql-community.repo"
  - name: Instalar dependencias hhtpd
    command: 'sudo dnf config-manager --disable mysql80-community'
  - name: Instalar dependencias hhtpd
    command: 'sudo dnf config-manager --enable mysql57-community'
  - name: Instalar dependencias hhtpd
    command: 'sudo dnf install mysql-community-server -y'
    

