---
- hosts: Rocky
  become: true
  become_method: sudo
  
  tasks:
  - name: Instalar dependencias remi1
    command: 'sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y'
  - name: Instalar dependencias remi2
    command: 'sudo dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y'
  - name: Instalar dependencias remi3
    command: 'sudo dnf module enable php:remi-7.4 -y'
  - name: Instalar dependencias remi4
    command: 'sudo dnf install php php-cli php-common -y'
    
    
  - name: Instalar dependencias hhtpd
    command: 'sudo dnf remove @mysql'
  - name: Instalar dependencias hhtpd
    command: 'sudo dnf module reset mysql'
  - name: Instalar dependencias hhtpd
    command: 'sudo dnf module disable mysql -y'
    

