---
- hosts: Rocky
  become: true
  become_method: sudo
  
  tasks:
  - name: Instalar dependencias remi1
    command: 'sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y'
  - name: Instalar dependencias remi2
    command: 'sudo dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y'
  - name: Instalar dependencias remi3
    command: 'sudo dnf module enable php:remi-7.4 -y'
  - name: Instalar dependencias remi4
    command: 'sudo dnf install php php-cli php-common -y'

    

