---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
   - vars/default.yml
  
  tasks:
  - name: Update
    command: 'sudo yum update -y'
  - name: Upgrade
    command: 'sudo yum upgrade -y'
  - name: Tools
    command: 'sudo yum install open-vm-tools unzip wget -y'
    
##PHP7.4
  - name: Instalar php1
    command: 'sudo dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y'
  - name: Instalar php2
    command: 'sudo dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y'
  - name: Instalar php3
    command: 'sudo dnf module enable php:remi-7.4 -y'
  - name: Instalar php4
    command: 'sudo dnf install php php-cli php-common php-mysqlnd -y'

##MYSQL5.7  
  - name: Instalar mysql1 
    command: 'dnf search open-vm'
  - name: Instalar mysql2
    command: 'sudo dnf install open-vm-tools.x86_64 -y'
  - name: Instalar mysql3
    command: 'sudo dnf remove @mysql'
  - name: Instalar mysql4
    command: 'sudo dnf module reset mysql'
  - name: Instalar mysql5 
    command: 'sudo dnf module disable mysql -y'
  - name: Instalar mysql6
    template:
      src: files/mysql-community.repo
      dest: /etc/yum.repos.d/mysql-community.repo
  - name: Instalar mysql7
    command: 'sudo dnf config-manager --disable mysql80-community'
    ignore_errors: yes
  - name: Instalar mysql8
    command: 'sudo dnf config-manager --enable mysql57-community'
  - name: Instalar mysql9
    command: 'sudo dnf install mysql-community-server -y'
  - name: Instalar mysql10 
    command: 'sudo systemctl enable --now mysqld.service'

##GIT
  - name: Instalar git1
    command: 'sudo dnf search git'
  - name: Instalar git2
    command: 'sudo dnf install git.x86_64 -y'

##SNMP
  - name: Instalar snmp1 
    command: 'sudo dnf install net-snmp -y'
  - name: Instalar snmp2
    template:
      src: files/snmpd.conf
      dest: /etc/snmp/snmpd.conf
  - name: Instalar snmp3 
    command: 'sudo systemctl enable snmpd'
  - name: Instalar snmp4 
    command: 'sudo systemctl start snmpd'

##HTTPD
  - name: Instalar httpd1 
    command: 'sudo yum install httpd -y'
  - name: Instalar httpd2
    command: 'sudo systemctl enable httpd'
  - name: Instalar httpd3
    command: 'sudo systemctl start httpd'
  - name: Instalar httpd4
    command: 'sudo mkdir /etc/httpd/sites-availabe /etc/httpd/sites-enabled /etc/httpd/ssl.crt /etc/httpd/ssl.key /var/www/marketplace'
  - name: Instalar httpd5
    template:
      src: files/httpd.conf
      dest: /etc/httpd/conf/httpd.conf
  - name: Instalar httpd6
    command: 'wget https://github.com/Karnaug/marketplace.git -P /var/www/marketplace'


    ##HTTPD##SSL
  - name: Instalar httpd-ssl1
    command: 'sudo dnf install mod_ssl -y'
  - name: Instalar httpd-ssl2
    template:
      src: files/ssl.conf
      dest: /etc/httpd/conf.d/ssl.conf

##IPTABLES
#  - name: Instalar iptables1
#    command: 'sudo dnf install iptables -y'
#  - name: Instalar iptables2
#    command: 'sudo dnf install iptables-services -y'
#  - name: Instalar iptables3
#    command: 'sudo systemctl enable iptables'
#  - name: Instalar iptables4
#    command: 'sudo service iptables start'
#  - name: Instalar httpd-ssl5
#    template:
#      src: "files/iptables-config"
#      dest: "/etc/sysconfig/iptables-config"
#  - name: Instalar httpd-ssl6
#    template:
#      src: "files/iptables"
#      dest: "/etc/sysconfig/iptables"
#  - name: Instalar iptables7
#    command: 'sudo service iptables restart'

##FIREWALLD
  - name: Deshabilitar firewalld
    command: 'sudo systemctl disable firewalld'
##IP
  - name: Configuraci칩n de red1
    lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-enp0s3 regexp="^IPADDR=" line="IPADDR={{ ipaddr }}" state=present
  - name: Configuraci칩n de red2
    lineinfile: dest=/etc/sysconfig/network-scripts/ifcfg-enp0s3 regexp="^GATEWAY=192.168.149.187" line="GATEWAY={{ gateway }}" state=present
  - name: Configuraci칩n de red3
    command: 'sudo systemctl restart NetworkManager.service'
##REBOOT
  - name: Reiniciar m치quina
    command: 'sudo reboot'
    ignore_errors: yes
    

