
---
- hosts: all
  become: true
  become_method: sudo
  
  tasks:
  - name: Update
    command: 'sudo yum update -y'
  - name: Upgrade
    command: 'sudo yum upgrade -y'
  - name: Tools
    dnf:
      name: 
        - open-vm-tools
        - git
      state: latest
      
##MYSQL5.7  
  - name: Instalar mysql1 
    command: 'dnf search open-vm'
  - name: Instalar mysql2
    command: 'sudo dnf install open-vm-tools.x86_64 -y'
  - name: Instalar mysql3
    command: 'sudo dnf remove @mysql'
  - name: Instalar mysql4
    command: 'sudo dnf module reset mysql'
  - name: Instalar mysql5 
    command: 'sudo dnf module disable mysql -y'
  - name: Instalar mysql6
    template:
      src: files/mysql-community.repo
      dest: /etc/yum.repos.d/mysql-community.repo
  - name: Instalar mysql7
    command: 'sudo dnf config-manager --disable mysql80-community'
    ignore_errors: yes
  - name: Instalar mysql8
    command: 'sudo dnf config-manager --enable mysql57-community'
  - name: Instalar mysql9
    command: 'sudo dnf install mysql-community-server -y'
  - name: Instalar mysql10 
    command: 'sudo systemctl enable --now mysqld.service'    



