
---
- hosts: all
  become: true
  become_method: sudo
  
  tasks:
  - name: Update
    command: 'sudo yum update -y'
  - name: Upgrade
    command: 'sudo yum upgrade -y'
  - name: Tools
    dnf:
      name: 
        - open-vm-tools
        - git
      state: latest
    
##MYSQL5.7  
  - name: Instalar mysql(1/4) 
    command:   sudo dnf {{ item }}    
    with_items:
      - search open-vm
      - install open-vm-tools.x86_64 -y
      - remove @mysql 
      - module reset mysql 
      - module disable mysql -y 
  - name: Instalar mysql(2/4)
    template:
      src: files/mysql-community.repo
      dest: /etc/yum.repos.d/mysql-community.repo
  - name: Instalar mysql(3/4) 
    command:   sudo dnf {{ item }}    
    with_items:
      - config-manager --disable mysql80-community
      - dnf config-manager --enable mysql57-community
      - install mysql-community-server -y
      - module reset mysql
      - module disable mysql -y
    ignore_errors: yes
  - name: Instalar mysql(4/4) 
    command: 'sudo systemctl enable --now mysqld.service'



