
---
- hosts: all
  become: true
  become_method: sudo
  
  tasks:
  - name: Update
    command: 'sudo yum update -y'
  - name: Upgrade
    command: 'sudo yum upgrade -y'
  - name: Tools
    dnf:
      name: 
        - open-vm-tools
        - git
        - mysql-server
      state: latest 
