---
- hosts: all
  become: true
  become_method: sudo

  tasks:
  - name: Update
    command: 'sudo yum update -y'
  - name: Upgrade
    command: 'sudo yum upgrade -y'

##MYSQL5.7  
- name: Install mysql = 5.7
  dnf:
    name: httpd=5.7
    state: present



