---
- name: Install MySQL
  hosts: all
  become: true
  become_method: sudo
  
  tasks:
    - name: "Installing Repo"
      shell: sudo rpm -Uvh http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm
      ignore_errors: yes
    - name: "Installing MySQL 5.7"
      dnf:
        name: 
          - mysql-community-server
        state: present
    - name: Start the MySQL service
      become: true
      service: 
        name: mysqld
        state: started
        enabled: true
    - debug: var=mysql_root_pass.stdout
    



