
---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
   - vars/default.yml

  tasks:
  - name: Update
    command: 'sudo yum update -y'
  - name: Upgrade
    command: 'sudo yum upgrade -y'
  - name: Tools
    dnf:
      name: 
        - open-vm-tools
        - git
      state: latest

 ##PHP7.4
  - name: Instalar php
    command:   sudo dnf {{ item }} -y   
    with_items:
      - install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm 
      - install https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      - module enable php:remi-7.4
      - install php php-cli php-common php-mysqlnd   

