
---
- hosts: all
  become: true
  become_method: sudo
  
##CENTOS
  tasks:
  - name: Update
    command: 'sudo yum update -y'
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  - name: Upgrade
    command: 'sudo yum upgrade -y'
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  - name: Tools
    dnf:
      name: 
        - open-vm-tools
        - git
        - php
        - php-cli
        - php-common
        - php-mysqlnd
      state: latest
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
